#!/usr/local/sbin/charm-env python3

from lib_matrix import MatrixHelper
from charmhelpers.core import hookenv

matrix = MatrixHelper()
name = hookenv.action_get('name')
password = hookenv.action_get('pass')
admin = hookenv.action_get('admin')
err = matrix.register_user(name, password=password, admin=admin)

if err:
    hookenv.action_fail(err)

msg = "Successfully registered user {} on {}.".format(
        name, hookenv.local_unit())
hookenv.action_set({'outcome': 'success',
                    'message': msg })

# vim: set ft=python
