#!/usr/local/sbin/charm-env python3

from lib_matrix import MatrixHelper
from charmhelpers.core import hookenv

matrix = MatrixHelper()
name = hookenv.action_get('name')
password = hookenv.action_get('pass')
err = matrix.set_password(name, password)

if err:
    hookenv.action_fail(err)

msg = "Successfully set password for user {} on {}.".format(
        name, hookenv.local_unit())
hookenv.action_set({'outcome': 'success',
                    'message': msg })

# vim: set ft=python
