#!/usr/local/sbin/charm-env python3
"""Set user password."""

from lib_matrix import MatrixHelper
from charmhelpers.core import hookenv

matrix = MatrixHelper()
name = hookenv.action_get("user")
password = hookenv.action_get("pass")

if name and password:
    err = matrix.set_password(name, password)

    if err:
        hookenv.action_fail(err)

    msg = "Successfully set password for user {} on {}.".format(
        name, hookenv.local_unit()
    )
    hookenv.action_set({"outcome": "success", "message": msg})
else:
    hookenv.action_fail("Please provide user and pass as parameters.")

# vim: set ft=python
